// vue-react/tongxing/src/components/Modal.vue
<template>
  <div v-if="isVisible" class="modal-overlay">
    <div class="modal">
      <h2>我是弹窗</h2>
      <p>这是一个简单的弹窗示例。</p>
      <button @click="close">关闭</button>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { defineExpose } from 'vue';

const isVisible = ref(false);

// 定义方法来控制弹窗的显示和隐藏
const open = () => {
  isVisible.value = true;
};

const close = () => {
  isVisible.value = false;
};

// 暴露方法给父组件
defineExpose({
  open,
  close
});
</script>

<style scoped>
.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.5);
  display: flex;
  justify-content: center;
  align-items: center;
}

.modal {
  background-color: white;
  padding: 20px;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.3);
}
</style>

// react/basic/forwardRef/demo/src/Modal.jsx
import { forwardRef, useImperativeHandle, useState } from "react";

const Modal = forwardRef((props, ref) => {
  const [visible, setVisible] = useState(false);

  // 向父组件暴露的方法
  useImperativeHandle(ref, () => ({
    open() {
      setVisible(true);
    },
    close() {
      setVisible(false);
    }
  }));

  if (!visible) return null;

  return (
    <div style={overlayStyle}>
      <div style={modalStyle}>
        <h3>我是 Modal</h3>
        <button onClick={() => setVisible(false)}>内部关闭</button>
      </div>
    </div>
  );
});

export default Modal;

// 简单样式
const overlayStyle = {
  position: "fixed",
  // inset: 0,
  top: "30%",
  left: "30%",
  right: "30%",
  bottom: "30%",
  background: "rgba(0,0,0,0.5)",
  display: "flex",
  alignItems: "center",
  justifyContent: "center"
};

const modalStyle = {
  background: "#fff",
  padding: 20,
  borderRadius: 8
};
