// vue-react/vue-elements/src/views/Login.vue
<template>
  <el-form
    style="position: absolute; left: 45%; "
    ref="formRef"
    :model="form"
    label-width="auto"
  >
    <el-form-item label="用户名">
      <el-input v-model="form.name" size="small"/>
    </el-form-item>

     <el-form-item label="密码">
      <el-input v-model="form.password" type="password" size="small"/>
    </el-form-item>
   
    <el-form-item>
      <el-button
        type="primary"
        @click="onSubmit"
        :loading="loading"
      >
        登录
      </el-button>
    </el-form-item>
  </el-form>
</template>

<script setup>
  import { ref, reactive, toRefs } from 'vue'
  import {login} from '../api/apis'
  import { Message } from 'element3'
  import {useRouter} from 'vue-router'
  
  const formRef = ref(null)
  const loading = ref(false)
  const form = reactive({
      name: '',
      password: ''
  })
  const router = useRouter()

  const onSubmit = async () => {
    loading.value = true
    try{
      const res = await login(form)
      console.log(res);
      router.replace('/')
    }catch(error){
      Message({
        type: 'warning',
        message: error
      })
    }finally{
      loading.value = false
    }
  }

      
    
</script>

// react/basic/jwt/jwt-demo/src/pages/Login.jsx
import React, { useState } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { login } from '../api';
import { useAuth } from '../hooks/useAuth';

function Login() {
  const { dispatch } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();

  const from = location.state?.from || '/';

  const [formData, setFormData] = useState({
    username: '',
    password: '',
  });

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleLogin = async (e) => {
    e.preventDefault();
    try {
      const res = await login(formData);
      console.log(res);
      localStorage.setItem('token', res.token);
      dispatch({ type: 'LOGIN', payload: res });
      navigate(from, { replace: true });
    } catch (err) {
      alert('登录失败');
      console.error(err);
    }
  };

  return (
    <div>
      <h2>Login Page</h2>
      <form onSubmit={handleLogin}>
        <div>
          <label>
            Username: 
            <input
              type="text"
              name="username"
              value={formData.username}
              onChange={handleChange}
              required
            />
          </label>
        </div>
        <div>
          <label>
            Password: 
            <input
              type="password"
              name="password"
              value={formData.password}
              onChange={handleChange}
              required
            />
          </label>
        </div>
        <button type="submit">Login</button>
      </form>
    </div>
  );
}

export default Login;
