// vue-react/cli/hello-vue/src/components/Counter.vue
<template>
  <div class="counter">
    <!-- 显示 count 的值 -->
    <p>Count: {{ count }}</p>
    <!-- 按钮，点击后调用 increment 方法 -->
    <button @click="increment">+1</button>
  </div>
</template>

<script setup>
import { ref } from 'vue';

// 定义响应式数据
const count = ref(0);

// 定义方法
const increment = () => {
  count.value++;
};
</script>

<style scoped>
/* 添加一些简单的样式 */
.counter {
  font-family: Arial, sans-serif;
  text-align: center;
  margin-top: 50px;
}

button {
  padding: 10px 20px;
  font-size: 16px;
}
</style>

// vue-react/cli/hello-react/src/components/Counter/index.jsx
// Counter.js

import React, { useState } from 'react';
import './index.css'; // 引入本地样式文件

function Counter() {
  // 定义响应式数据
  const [count, setCount] = useState(0);

  // 定义方法
  const increment = () => {
    setCount(count + 1);
  };

  return (
    <div className="counter">
      {/* 显示 count 的值 */}
      <p>Count: {count}</p>
      {/* 按钮，点击后调用 increment 方法 */}
      <button onClick={increment}>+1</button>
    </div>
  );
}

export default Counter;
