// interview/2025_chun/vue/vuex/vuex-counter/src/Counter.vue
<template>
  <div id="app">
    Clicked: {{ count }} times, count is {{ evenOrOdd }}.
    <button @click="increment">+</button>
    <button @click="decrement">-</button>
    <button @click="incrementIfOdd">Increment if odd</button>
    <button @click="incrementAsync">Increment async</button>
  </div>
</template>

<script setup>
import { computed } from 'vue'
import { useStore } from 'vuex'
const store = useStore()
// 不用 computed 没有依赖 计算属性自动缓存 并依赖
const count =  computed(() => store.state.count)
const evenOrOdd =  computed(() => store.getters.evenOrOdd)
const increment =  () => store.dispatch('increment')
const decrement =  () => store.dispatch('decrement')
const incrementIfOdd = () => store.dispatch('incrementIfOdd')
const incrementAsync =  () => store.dispatch('incrementAsync')
</script>

<style scoped>

</style>

// react/zustand/zustand-counter/src/Counter.tsx
// Counter.js
import React from 'react';
import useCounterStore from './store';

function Counter() {
  const count = useCounterStore((state) => state.count);
  const increment = useCounterStore((state) => state.increment);
  const decrement = useCounterStore((state) => state.decrement);

  return (
    <div>
      <h1>Count: {count}</h1>
      <button onClick={increment}>Increment</button>
      <button onClick={decrement}>Decrement</button>
    </div>
  );
}

export default Counter;
